<div id="page:main-container" class="page-columns">
    <div id="container" class="main-col">
    <div class="admin__old" style="float: right;width: 70%;">
        <div>
            <div class="entry-edit form-inline">
                <div data-area-active="true">
                    <div class="admin__scope-old">
                        <div class="fieldset-wrapper customer-information" style="padding-left: 12px;">
                            You can chat by clicking on the customer name on the left tab.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php echo $block->getChildHtml();?>
    </div>
</div>