<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()): ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?= $block->escapeHtml(
                    __(
                        'Records %1 to %2 of %3 total',
                        $localeFormatter->formatNumber($block->getFirstNum()),
                        $localeFormatter->formatNumber($block->getLastNum()),
                        $localeFormatter->formatNumber($block->getTotalNum())
                    )
                ) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?= $block->escapeHtml(__('%1 Record', $localeFormatter->formatNumber($block->getTotalNum()))) ?>
            <?php else: ?>
                <?= $block->escapeHtml(__('%1 Record(s)', $localeFormatter->formatNumber($block->getTotalNum()))) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages" style="display: inline;margin-left: 6px;">
            <strong class="label pages-label" id="paging-label"><?= $block->escapeHtml(__('Page')) ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
            <?php if (!$block->isFirstPage()): ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?= $block->escapeHtmlAttr($text ? 'link ' : 'action ') ?> previous"
                       href="<?= $block->escapeUrl($block->getPreviousPageUrl()) ?>"
                       title="<?= $block->escapeHtmlAttr($text ? $text : __('Previous')) ?>">
                        <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                        <span><?= $block->escapeHtml($text ? $text : __('Previous')) ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()): ?>
                <li class="item">
                    <a class="page first" href="<?= $block->escapeUrl($block->getFirstPageUrl()) ?>">
                        <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                        <span><?= $block->escapeHtml($localeFormatter->formatNumber(1)) ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()): ?>
                <li class="item">
                    <a class="page previous jump"
                       title=""
                       aria-label="<?= $escaper->escapeHtmlAttr(__(
                           'Skip to page %1',
                           $localeFormatter->formatNumber($block->getPreviousJumpPage())
                       )) ?>"
                       href="<?= $block->escapeUrl($block->getPreviousJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page)): ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?= $block->escapeHtml(__('You\'re currently reading page')) ?></span>
                            <span><?= $block->escapeHtml($localeFormatter->formatNumber($_page)) ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?= $block->escapeUrl($block->getPageUrl($_page)) ?>" class="page">
                            <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                            <span><?= $block->escapeHtml($localeFormatter->formatNumber($_page)) ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()): ?>
                <li class="item">
                    <a class="page next jump"
                       title=""
                       aria-label="<?= $escaper->escapeHtmlAttr(__(
                           'Skip to page %1',
                           $localeFormatter->formatNumber($block->getNextJumpPage())
                       )) ?>"
                       href="<?= $block->escapeUrl($block->getNextJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()): ?>
              <li class="item">
                  <a class="page last" href="<?= $block->escapeUrl($block->getLastPageUrl()) ?>">
                      <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                      <span><?= $block->escapeHtml($localeFormatter->formatNumber($block->getLastPageNum())) ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()): ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?= /* @noEscape */ $text ? 'link ' : 'action ' ?> next"
                       href="<?= $block->escapeUrl($block->getNextPageUrl()) ?>"
                       title="<?= $block->escapeHtmlAttr($text ? $text : __('Next')) ?>">
                        <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                        <span><?= $block->escapeHtml($text ? $text : __('Next')) ?></span>
                    </a>
                </li>
            <?php endif;?>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="limiter" style="padding-top: 8px;width: 270px;">
            <strong class="limiter-label"><?= $block->escapeHtml(__('Show')) ?></strong>
            <select id="limiter" class="limiter-options" style="width: 60px;">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?= $block->escapeUrl($block->getLimitUrl($_key)) ?>"
                        <?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($localeFormatter->formatNumber((int) $_limit)) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?= $block->escapeHtml(__('per page')) ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>

<script type="text/javascript">
    require(['jquery'], function(jQuery){
        jQuery(document).ready(function(){
            jQuery('#limiter').change(function(){
                var newUrl = jQuery(this).val();
                location.href=newUrl;
            }); 
        });
    });
</script>


<style type="text/css">
@media (min-width: 768px), print {
  .toolbar-amount {
    display: block;
    float: left;
    position: static;
  }
}
.toolbar-amount {
  left: 0;
  line-height: 18px;
  margin: 0;
  padding: 7px 0;
  text-align: left;
  top: 0;
  vertical-align: middle;
}
.toolbar-amount {
  line-height: 18px;
  text-align: left;
}
.pages > .label {
  border: 0;
  clip: rect(0, 0, 0, 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
b, strong {
  font-weight: 700;
}
.pages .items {
  font-size: 0;
  letter-spacing: -1px;
  line-height: 0;
  white-space: nowrap;
  margin: 0;
  padding: 0;
  list-style: none none;
  display: inline-block;
  font-weight: 400;
}
.pages .item {
  font-size: 1.2rem;
  line-height: 3rem;
  letter-spacing: normal;
  margin: 0 8px 0 0;
  display: inline-block;
}
.pages strong.page {
  background: #e5e5e5;
  font-size: 1.2rem;
  line-height: 3rem;
  letter-spacing: normal;
  color: #333;
  display: inline-block;
  font-weight: 700;
  padding: 0 5px;
}
.pages .item .label {
  border: 0;
  clip: rect(0, 0, 0, 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
.pages strong.page {
  font-size: 1.2rem;
  line-height: 3rem;
  letter-spacing: normal;
  color: #333;
  font-weight: 700;
}
.pages a.page {
  color: #006bb4;
  display: inline-block;
  padding: 0 5px;
  text-decoration: none;
}
.pages a.page {
  color: #006bb4;
}
.pages .action.next {
  margin-left: 8px;
}
.pages .action.next {
  display: inline-block;
  text-decoration: none;
}
.pages .action {
  box-shadow: inset 0 1px 0 0 #fff,inset 0 -1px 0 0 rgba(204,204,204,0.3);
  border-radius: 3px;
  padding: 0 8px;
}
.pages .action {
  background: #f0f0f0;
  border: 1px solid #ccc;
  color: #7d7d7d;
  display: inline-block;
  padding: 0;
  text-decoration: none;
}
.pages .action {
  color: #000;
}
.pages .action.next {
  margin-left: 8px;
}
.pages .action.next {
  display: inline-block;
  text-decoration: none;
}
.pages .action {
  box-shadow: inset 0 1px 0 0 #fff,inset 0 -1px 0 0 rgba(204,204,204,0.3);
  border-radius: 3px;
  padding: 0 8px;
}
.limiter-label {
  font-weight: 400;
}
.limiter-options {
  margin: 0 5px 0 7px;
  width: auto;
}
select {
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  appearance: none;
  background-size: 30px 60px;
  text-indent: .01em;
  text-overflow: '';
}
select {
  background: #fff url('../images/select-bg.svg') no-repeat 100% 45%;
    background-size: auto;
    background-clip: border-box;
  background-clip: padding-box;
  border: 1px solid #ccc;
  border-radius: 1px;
  font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;
  font-size: 14px;
  height: 32px;
  line-height: 1.42857143;
  padding: 4px 25px 5px 10px;
  vertical-align: baseline;
  width: 100%;
  box-sizing: border-box;
}
</style>