<form class="form contact" action="<?php echo $this->getUrl('ticket/customer/post');?>" id="ticket-form" method="post" enctype="multipart/form-data">    
    <fieldset class="fieldset">
        <legend class="legend"><span>Please provide the detail about the issue you are facing and need a resolution with.</span></legend><br>
        <div class="field note no-label">
            You can expect a reply in less than 24 hours from our Support Team.        </div>
        <div class="field subject required">
            <label class="label" for="subject"><span>Subject</span></label>
            <div class="control">
                <input name="subject" id="subject" title="Subject" value="" class="input-text" type="text">
            </div>
        </div>
        <div class="field details required">
            <label class="label" for="details">
                <span>Issue Details</span>
            </label>
            <div class="control">
                <textarea name="details" id="details" title="details of the issue" class="input-text" cols="5" rows="3" aria-required="true"></textarea>
            </div>
        </div>
        <div class="field priority required">
            <label class="label" for="priority"><span>Issue Priority</span></label>
            <div class="control">
                <select name="priority" id="priority" title="Priority" class="input-text" style="width:100px;">
                    <option value="high">High</option>    
                    <option value="medium" selected="selected">Medium</option>
                    <option value="low">Low</option>
                </select>
            </div>
        </div>
        <div class="field file_path">
            <label class="label" for="file_path"><span>Attach File</span></label>
            <div class="control">
                <input type="file" name="file_path" id="file_path" title="file_path" class="input-file"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <!--<input type="hidden" name="hideit" id="hideit" value="">-->
            <button type="submit" title="Submit" class="action submit primary" id="submit" name="submit">
                <span>Submit</span>
            </button>
        </div>
        <div class="secondary">
            <button type="button" title="Back" class="secondary" id="back" name="back">
                <span>Back</span>
            </button>
        </div>
    </div>
</form>
<script type="text/javascript">
    requirejs(['jquery'], function(jQuery){
        jQuery(function(){
            jQuery(document).ready(function(){
                jQuery('#back').click(function(){
                    location.href="<?php echo $this->getUrl('ticket/customer/index');?>"
                });
            });
        });
    });
</script>