<span class="price-container">
    <span class="price-label">Price</span>
    <div class="control giftcard-price">
        <div class="price-error"></div>
        <span id="currency-symbol"><?= /* @noEscape */ $block->getPriceCurrency()->getCurrencySymbol();?></span>
        <input name="Giftcard Price" id="giftcard_price" value="" title="giftcard_price" class="input-number" type="number">
    </div>
</span>