<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>   
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass) : ?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">    
            <?= $block->getColumnHtml($_item, $columnName) ?>
            <?php if ($columnName == "product" ){                
                $options = $_item->getProductOptions();
                if($_item->getProductType()=="reservation"){
                    echo "Reservation Name: " .  $options['info_buyRequest']['reservation_name']."<br />";
                    echo "Reservation Date : " .  $options['info_buyRequest']['reservation_date']."<br />";
                }             
            } ?>
        </td>
    <?php endforeach; ?>
</tr>
