<?php
if($this->getQuote()->hasItems()){
?>
    <div class="giftcard-cart-discount">
        <div class="block discount active" id="giftcard_discount_block">
            <div class="title">
                <strong>Apply Giftcard Discount Code</strong>
            </div>
            <div class="content">
                <form id="giftcard-discount-form" action="<?= /* @noEscape */ $this->getUrl('giftcard/cart/apply') ?>" method="post">
                    <div class="fieldset coupon">
                        <?php
                        $appliedGiftcard = $block->getAppliedGiftcard();
                        ?>
                        <input name="remove_giftcard" id="remove_giftcard" value="<?php echo ($appliedGiftcard) ? 1 : 0;?>" type="hidden"/>
                        <div class="field">
                            <div class="control">
                                <input class="input-text" id="giftcard_code" name="giftcard_code" value="<?= /* @noEscape */ ($appliedGiftcard) ? $appliedGiftcard : "";?>" placeholder="Enter Giftcard Discount Code" type="text" />
                            </div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <?php if($appliedGiftcard){?>
                                    <button class="action giftcard_button" type="button" value="Remove Giftcard">
                                        <span>Remove Giftcard</span>
                                    </button>
                                <?php }else{?>
                                    <button class="action giftcard_button" type="button" value="Apply Giftcard">
                                        <span>Apply Giftcard</span>
                                    </button>
                                <?php }?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php
}
?>
<script type="text/javascript">

    requirejs(['jquery'], function(jQuery) {
        jQuery(function () {
            jQuery('.giftcard_button').click(function(){
                var giftcardNumber = jQuery('#giftcard_code').val();
                jQuery('#giftcard-discount-form').submit();
            });
        });
    });
</script>
<style type="text/css">
    .giftcard-cart-discount{
        padding: 10px 0px 10px 0px;
        width:40%;
        color:orange;
    }
    .giftcard_button{
        background: orange;
        border: 1px solid orange;
        box-shadow: none !important;
    }
</style>
