<input id="giftcard-value-only" style="display: none" value="<?= /* @noEscape */ $this->getGiftcardValue();?>" type="hidden" />
<input id="giftcard-value-max" style="display: none" value="<?= /* @noEscape */ $this->getGiftcardMaxPrice();?>" type="hidden" />
<input id="giftcard-store-currency" style="display: none" value="<?= /* @noEscape */ $this->getStoreCurrency();?>" type="hidden" />
<input id="giftcard-shipping-price" style="display: none" value="<?= /* @noEscape */ $this->getShippingPrice();?>" type="hidden" />